[REVIEW] #88 - Criar rota, controller e função de obter dados do Banco de Dados
Eccoar/2020.2-Eccoar_Complaint pull request #1
Opened 2021-03-20 02:42 UTC by Victor-Buendia

## Conteúdo
Realização do serviço de request de todos os bancos de dados do back, com paginação.

    Neste pull request se realizou:

- Criação da rota /api/complaints
- Criação da função que puxa dados do banco
- Criação da controller que media o request pro banco
- Paginação dos dados no back
 
 ## Issue correspondente
Issue número #88.

2021-03-20 17:14 UTC, Phe0 approved these changes

2021-03-20 18:05 UTC, devsalula requested changes
Guys, parabéns pelo trabalho! É muito nítido o crescimento do aprendizado de vocês.
Daí só queria que vcs removessem o que eu pedi e dessem uma olhada na modificação do orderDate que pedi também (se não der certo, tudo bem, a gente vê isso mais para frente).

2021-03-20 18:05 UTC, devsalula commented on src/repositories/ComplaintRepository.ts
> +            take: take,
Uma coisa que queria pedir. Vocês conseguem pedir para ordenar o retorno dessa query pela data de criação das denúncias?
Tipo, vocês passam como parâmetro lá na controller um `resp.query.orderDate`que só aceita o valor 'ASC' e 'DESC'.
E aqui na query para o banco, vocês fazem uma parada tipo:
```
const [result, count] = await repository.findAndCount({
            skip: skip * take,
            take: take,
            order: {creation_date: orderDate},
        });
```

2021-03-21 00:20 UTC, Victor-Buendia commented
Resolvido!

2021-03-21 00:31 UTC, devsalula approved these changes
Ótimo trabalho @Victor-Buendia e @luiz-herique !!! Ficou muito bom!

2021-03-21 00:31 UTC, merged