Solve #125 US17 Página de detalhamento de denúncia
Eccoar/2020.2-Eccoar_Complaint pull request #10
Opened 2021-04-03 12:14 UTC by Victor-Buendia

## Conteúdo

Neste pull request foi criada uma função para pegar os detalhes de um card e se há um voto nele pelo usuário.

Neste pull request se realizou:

- Criação da função getComplaintWithVote
- Testes do teste

## Checklist

- [ ] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [ ] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ ] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [ ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ ] Escrever o título do pull request no formato correto, conforme as referências abaixo:

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:

- Solve #X IssueName (Caso Padrão)
- WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-04-03 15:30 UTC, devsalula requested changes

2021-04-03 15:30 UTC, devsalula commented on src/routes.ts
> +routers.get("/api/complaint/withVote", (req: Request, res:Response) => {
Por uma questão de taxonomia e boa leitura, troca o nome dessa rota para `api/complaint/votes`. Não esquece de mudar no Gateway.

2021-04-05 19:32 UTC, Victor-Buendia commented
Pronto, @devsalula !

2021-04-05 23:13 UTC, devsalula approved these changes

2021-04-06 00:05 UTC, MatheusBlanco approved these changes

2021-04-06 00:05 UTC, merged