WIP #146 Refatorar código do serviço de complaint
Eccoar/2020.2-Eccoar_Complaint pull request #12
Opened 2021-04-10 12:52 UTC by luiz-herique

## Conteúdo

Neste pull request está se realizando:

 Padronizar código em todo o repositório
 Criar camada de services

2021-04-10 16:03 UTC, MatheusBlanco commented
Gente, como está a situação deste PR? O que foi feito?

2021-04-10 16:47 UTC, devsalula requested changes
Galera legal trabalho! 🚀 
Mas código comentado não pode ser merjado. Pfvr, corrijam as funções que vocês comentaram.

2021-04-10 16:47 UTC, devsalula commented on src/services/VotesService.ts
> +/*
Se está comentado, é pq não vai utilizar no código. Nesse caso você apaga o código ou descomenta.

2021-04-10 16:47 UTC, devsalula commented on src/routes.ts
> +/*
Se está comentado, é pq não vai utilizar no código. Nesse caso você apaga o código ou descomenta.

2021-04-10 16:47 UTC, devsalula commented on src/controllers/ControllerComplaint.ts
> +/*
Se está comentado, é pq não vai utilizar no código. Nesse caso você apaga o código ou descomenta.

2021-04-10 21:15 UTC, MatheusBlanco requested changes
Gente, pedi algumas alterações aqui. E duas dúvidas, não tiveram novos testes, certo? E eu vi que algumas funções na controller estão com if/else, outras estão com try/catch. Ainda vão mexer nisso? Tentaram padronizar? Ou os outros EPS deram algum comentário sobre?

2021-04-10 21:15 UTC, MatheusBlanco commented on src/controllers/ControllerComplaint.ts
> +            console.log("Catch da create ");
Tirem esse console.log daqui

2021-04-10 21:15 UTC, MatheusBlanco commented on src/repositories/ComplaintRepository.ts
>    }
Acho que não foi parte das alterações de vocês, mas a partir de agora type any não vai ser mais aceito pelo eslint. Tem umas promises aqui que estão com este tipo

2021-04-10 21:15 UTC, MatheusBlanco commented on src/services/ComplaintService.ts
> +import { BadRequest, NotFound } from "../utils/Error";
Este BadRequest não está sendo utilizado, podem tirar. Deixem-o se forem usar em algum lugar

2021-04-11 23:38 UTC, luiz-herique commented on src/routes.ts
> +/*
Corrigido, os codigos nessesarios foram descometados e os outros foram excluidos

2021-04-11 23:38 UTC, luiz-herique commented on src/controllers/ControllerComplaint.ts
> +/*
Corrigido, os codigos nessesarios foram descometados e os outros foram excluidos

2021-04-11 23:39 UTC, luiz-herique commented on src/controllers/ControllerComplaint.ts
> +            console.log("Catch da create ");
O console.log excluido como recomendado

2021-04-11 23:39 UTC, luiz-herique commented on src/services/ComplaintService.ts
> +import { BadRequest, NotFound } from "../utils/Error";
Import desnessesario excluido.

2021-04-11 23:42 UTC, luiz-herique commented on src/controllers/ControllerComplaint.ts
> +            console.log("Catch da create ");
Sim, sem novos testes, apenas alterações em alguns dos que já aviam. Quanto a alteração do if else por try cacth foi conversado que não seria nesessario visto que os dois tem funções distintas, porém será adicionado tratamento de erro nas funções que nessecitam

2021-04-16 22:13 UTC, devsalula approved these changes

2021-04-16 22:14 UTC, devsalula requested changes
Ultima coisa, antes de merjar o pr de vcs. Façam um rebase com a main pfvr!

2021-05-08 15:52 UTC, closed without merging