Solve #159 Configurar migrações
Eccoar/2020.2-Eccoar_Complaint pull request #15
Opened 2021-04-16 13:47 UTC by Phe0

## Conteúdo

Foram configuradas as migrations para fazer as alterações necessárias ao banco.

Neste pull request se realizou:

- Configuradas migrations
- Service de migration adicionada ao docker-compose

## Checklist

- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo:

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:

- Solve #X IssueName (Caso Padrão)
- WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-04-17 21:09 UTC, MatheusBlanco requested changes
Show! Só queria que desse uma olhada no banco, tem algumas horas que não estou conseguindo criar uma denúncia, mas outras horas consigo normalmente. E parece ser meio aleatório. Tentei com uns textos aleatórios, todas as categorias e pulando a tela de foto ou não, mas não pareceu seguir um padrão. Das 6 ou 7 tentativas, 2 deram errado, e vendo no networks os dados que ele manda, parecem estar corretos.

 Ele dá esse log de erro quando dá problema:
![image](https://user-images.githubusercontent.com/37380789/115126713-a31eed80-9fa7-11eb-836d-97897a173d46.png)

Comentando o service de migrations do docker-compose pareceu resolver, mas tirou as migrações

2021-04-20 14:02 UTC, MatheusBlanco commented
@Phe0 , eu fui testar aqui de novo, e acho que o problema mesmo era com o meu computador. Agora que instalei um novo sistema, ele está rodando normal. Você pode testar no seu sistema e me falar como está aí? Se estiver tudo certo eu já aprovo

2021-04-20 18:43 UTC, Phe0 commented
aqui funcionou normal @MatheusBlanco

2021-04-20 18:43 UTC, MatheusBlanco approved these changes

2021-04-20 18:43 UTC, MatheusBlanco commented
Era meu PC me zoando msm.

2021-04-21 02:46 UTC, Victor-Buendia approved these changes
Sensacional seu trabalho, Pedro! Continue assim.

2021-04-21 02:46 UTC, merged