Solve #153 Retirada de denúncia
Eccoar/2020.2-Eccoar_Complaint pull request #18
Opened 2021-04-17 02:15 UTC by luiz-herique

## Conteúdo

Neste pull request se realizou:

- Criação da função responsável por remover voto;
- Teste da nova função

## Checklist

- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-04-17 15:43 UTC, MatheusBlanco requested changes
Boa galera! Dêem uma olhada nas correções pfvr, mas arrasaram mt!

2021-04-17 15:43 UTC, MatheusBlanco commented on src/controllers/ControllerComplaint.ts
> +	async delete(req: Request, res: Response): Promise<Response> {
Mudem o nome dessa controller para algo mais explícito, tipo deleteComplaintController ou algo parecido. Só para que possa ficar mais fácil de identificar

2021-04-17 23:56 UTC, luiz-herique commented on src/controllers/ControllerComplaint.ts
> +	async delete(req: Request, res: Response): Promise<Response> {
Obrigado pelo feedback, alteração realizada como solicitado.

2021-04-18 00:08 UTC, MatheusBlanco commented on src/controllers/ControllerComplaint.ts
> +	async delete(req: Request, res: Response): Promise<Response> {
Boa

2021-04-18 00:20 UTC, MatheusBlanco approved these changes

2021-04-24 17:00 UTC, devsalula requested changes
Galera, parabéns pelo trabalho, ficou muito bom.
Deixei alguns comentários para vocês darem uma olhada.
Gostaria de pedir também para vocês escreverem teste para a função de deletar que vocês criaram no ComplaintRepository.

Uma dúvida que eu fiquei, o que aconteceu com os votos de uma denúncia deletada? Eles estão sendo deletados, também?

2021-04-26 23:29 UTC, devsalula requested changes
Guys, ainda tem coisa que pedi que não foi solucionada. Por favor, olhem novamente.

Outra coisa, ainda não vi o que vocês fazem com os votos quando a denúncia é deletada.

2021-04-26 23:29 UTC, devsalula commented on src/controllers/ControllerComplaint.ts
> +			if (Number(complaint.userId) == Number(req.query.userId)) {
@luiz-herique aqui ainda não teve solução

2021-04-26 23:29 UTC, devsalula commented on src/repositories/ComplaintRepository.ts
> +	async deleteComplaint(id: number): Promise<void> {
Eu vi que vocês escreveram os testes. Mas vocês não testaram esse método em específico aqui.

2021-04-26 23:29 UTC, devsalula commented on test/repository.test.ts
> +		const result = await repository.getById(1);
Eu solicitei para testar o `deleteComplaint` e não o `getById`

2021-05-04 18:36 UTC, devsalula approved these changes
Nice Work! 🚀

2021-05-05 16:26 UTC, merged