Solve #167 Listar denúncias próximas do usuário
Eccoar/2020.2-Eccoar_Complaint pull request #19
Opened 2021-04-30 14:31 UTC by Victor-Buendia

## Conteúdo

- Implementação de uma lógica nova para o método de listar denúncias através do uso de longitude e lagitude dentro de um raio de 2km

Neste pull request se realizou:

- US - Filtro de denúncia por localização
- Testes da implementação nova no repositório

## Checklist

- [ ] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [ ] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ ] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [ ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ ] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-05-01 15:01 UTC, MatheusBlanco requested changes
Perfeita a funcionalidade. Dá uma olhadinha nos comentários, principalmente na parte de testes por favor

2021-05-08 18:18 UTC, devsalula requested changes

2021-05-08 18:18 UTC, devsalula commented on src/controllers/ControllerComplaint.ts
> +					Number(userId),
Aqui troca para String ao invés de Number

2021-05-08 18:18 UTC, devsalula commented on src/controllers/ControllerComplaint.ts
> +					Number(userId),
Aqui troca para String ao invés de Number

2021-05-08 18:18 UTC, devsalula commented on src/repositories/ComplaintRepository.ts
> +		userId: number,
Aqui troca para String ao invés de Number

2021-05-09 01:59 UTC, MatheusBlanco approved these changes

2021-05-09 02:26 UTC, Phe0 approved these changes

2021-05-15 19:11 UTC, devsalula approved these changes

2021-05-15 19:11 UTC, merged