Solve #165 Autenticação de usuário
Eccoar/2020.2-Eccoar_Complaint pull request #21
Opened 2021-05-03 21:29 UTC by DLBrianPina

Neste pull request se realizou:

- US 02
- Testes
- Alteração do tipo do id do usuário

2021-05-03 21:31 UTC, MatheusBlanco approved these changes
Boa galera

2021-05-03 22:03 UTC, MatheusBlanco requested changes
O rebase reescrever o userId do complaintMock em repository.test.ts de volta pra number. Só arrumar isso e eu re-aprovo

![image](https://user-images.githubusercontent.com/37380789/116939170-43c90a80-ac42-11eb-81fc-ae5aa684ae0a.png)

2021-05-04 17:38 UTC, MatheusBlanco approved these changes

2021-05-07 03:31 UTC, devsalula requested changes
Dá uma olhada com calma nos arquivos de seed, por favor.
Outra coisa, vai ser necessário gerar uma migração trocando o tipo do userId de number para string. Eu te ajudo se precisar.

2021-05-07 03:31 UTC, devsalula commented on db/seeds/voteData.ts
> +		userId: 'jiQQ7hyoAoM1iwWVAs9m0VMRnh5M',
Revisa todo esse arquivo de seed, tem vários votos que estão duplicados. Esse aqui é um deles.
Os votos duplicados estouram um erro no banco.

2021-05-08 15:54 UTC, devsalula approved these changes

2021-05-08 15:54 UTC, merged