Solve #124 Envio de e-mails
Eccoar/2020.2-Eccoar_Complaint pull request #9
Opened 2021-04-02 13:59 UTC by DLBrianPina

Neste pull request se realizou:

- US 26
- Filtragem de denúncias que estão em aguardo

2021-04-05 18:08 UTC, MatheusBlanco requested changes
Parabéns galera! Só lembrem de colocar os testes

2021-04-05 23:23 UTC, MatheusBlanco approved these changes

2021-04-10 15:20 UTC, Phe0 commented
@DLBrianPina @Arthur-Matos atualizem a branch com a devel, acho q fazendo isso vai passar na pipeline

2021-04-10 19:38 UTC, Phe0 commented
@DLBrianPina @Arthur-Matos conflito pra corrigir

2021-04-11 18:20 UTC, Phe0 approved these changes

2021-04-11 18:20 UTC, merged